#! /bin/sh

OS_RELEASE_FILE=${OS_RELEASE_FILE:-/etc/os-release}
SUDO=`which sudo`

pkgs_common='
coreutils
curl
dos2unix
file
gzip
wget
'

pkgs_pip='
conan
'

pkgs_alpine='
gnupg
py3-pip
minicom
sharutils
xxd
'

pkgs_alpine_edge='
cscope
'

pkgs_centos='
cscope
gnupg2
minicom
python3-pip
sharutils
vim-common
'

pkgs_debian='
cscope
gpg
minicom
python3-pip
sharutils
xxd
'

pkgs_fedora='
cscope
gnupg2
minicom
python3-pip
sharutils
vim-common
'

pkgs_rhel='
gnupg2
python3-pip
vim-common
'

test -r $OS_RELEASE_FILE || exit

. $OS_RELEASE_FILE

case $ID in
    alpine)
        $SUDO apk update
        $SUDO apk add $pkgs_common $pkgs_alpine
        $SUDO apk add $pkgs_alpine_edge --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
        ;;
    centos)
        case $VERSION_ID in
            8)
                extra_repos=powertools
                ;;
            9)
                extra_repos=crb
                ;;
        esac
        $SUDO dnf --assumeyes config-manager --set-enabled $extra_repos
        $SUDO dnf --assumeyes --refresh install epel-release epel-next-release
        $SUDO dnf --assumeyes --refresh install --allowerasing $pkgs_common $pkgs_centos
        ;;
    debian|ubuntu)
        $SUDO apt-get --assume-yes update
        $SUDO apt-get --assume-yes install $pkgs_common $pkgs_debian
        ;;
    fedora)
        $SUDO dnf --assumeyes --refresh install $pkgs_common $pkgs_fedora
        ;;
    rhel)
        $SUDO dnf --assumeyes --refresh install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        $SUDO dnf --assumeyes --refresh install --allowerasing $pkgs_common $pkgs_rhel
        ;;
esac

$SUDO python3 -m pip install --upgrade $pkgs_pip
