#! /bin/sh

OS_RELEASE_FILE=${OS_RELEASE_FILE:-/etc/os-release}
SUDO=`which sudo`

pkgs_common='
coreutils
curl
dos2unix
file
gzip
minicom
sharutils
wget
'

pkgs_pip='
conan
'

pkgs_alpine='
gnupg
py3-pip
xxd
'

pkgs_alpine_edge='
cscope
'

pkgs_centos='
cscope
gnupg2
python3-pip
vim-common
'

pkgs_fedora='
cscope
gnupg2
python3-pip
vim-common
'

pkgs_ubuntu='
cscope
gpg
python3-pip
xxd
'

test -r $OS_RELEASE_FILE || exit

. $OS_RELEASE_FILE

case $ID in
    alpine)
        $SUDO apk add $pkgs_common $pkgs_alpine
        $SUDO apk add $pkgs_alpine_edge --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
        ;;
    centos)
        $SUDO dnf --assumeyes install $pkgs_common $pkgs_centos
        ;;
    centos)
        case $VERSION_ID in
            8)
                epel_repo=powertools
                pkgs_epel='
                epel-release
                epel-next-release
                '
                pkgs_centos="$pkgs_centos awscli ctags"
                ;;
            9)
                epel_repo=crb
                pkgs_epel='
                https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-release-9-2.el9.noarch.rpm
                https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-next-release-9-2.el9.noarch.rpm
                '
                ;;
        esac
        $SUDO dnf --assumeyes config-manager --set-enabled $epel_repo
        $SUDO dnf --assumeyes install $pkgs_epel
        $SUDO dnf --assumeyes install --allowerasing $pkgs_common $pkgs_centos
        ;;
    fedora)
        $SUDO dnf --assumeyes install $pkgs_common $pkgs_fedora
        ;;
    ubuntu)
        $SUDO apt-get --assume-yes install $pkgs_common $pkgs_ubuntu
        ;;
esac

$SUDO python3 -m pip install --upgrade $pkgs_pip
